apiVersion: v1
kind: List
items:
  - apiVersion: front.in-cloud.io/v1alpha1
    kind: Factory
    metadata:
      name: configmap-details
    spec:
      key: configmap-details
      sidebarTags:
        - configmap-sidebar
      withScrollableMainContentCard: true
      urlsToFetch:
        - "/api/clusters/{2}/k8s/api/v1/namespaces/{3}/configmaps/{6}"
      data:
        # Заголовок
        - type: antdFlex
          data:
            id: 1
            gap: 6
            align: center
            style:
              marginBottom: 24px
          children:
            - type: antdText
              data:
                id: 2
                text: CM
                title: ConfigMap
                style:
                  fontSize: 20px
                  lineHeight: 24px
                  padding: "0 9px"
                  borderRadius: "20px"
                  minWidth: 24
                  display: inline-block
                  textAlign: center
                  whiteSpace: nowrap
                  color: "#fff"
                  backgroundColor: "#40199a"
                  fontFamily: RedHatDisplay, Overpass, overpass, helvetica, arial, sans-serif
                  fontWeight: 400
            - type: parsedText
              data:
                id: 3
                text: "{reqsJsonPath[0]['.metadata.name']['-']}"
                style:
                  fontSize: 20px
                  lineHeight: 24px
                  fontFamily: RedHatDisplay, Overpass, overpass, helvetica, arial, sans-serif

        # Вкладки
        - type: antdTabs
          data:
            id: 4
            defaultActiveKey: details
            items:
              # Details
              - key: details
                label: Details
                children:
                  # Основная карточка
                  - type: ContentCard
                    data:
                      id: 5
                      style:
                        marginBottom: 24px
                    children:
                      - type: antdText
                        data:
                          id: 6
                          text: ConfigMap details
                          strong: true
                          style:
                            fontSize: 20px
                            marginBottom: 12px

                      - type: Spacer
                        data:
                          id: 7
                          $space: 16

                      - type: antdRow
                        data:
                          id: 8
                          gutter: [48, 12]
                        children:
                          # Левая колонка
                          - type: antdCol
                            data:
                              id: 9
                              span: 12
                            children:
                              - type: antdFlex
                                data:
                                  id: 10
                                  vertical: true
                                  gap: 24
                                children:
                                  - type: antdFlex
                                    data:
                                      id: 11
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 12
                                          text: Name
                                          strong: true
                                      - type: parsedText
                                        data:
                                          id: 13
                                          text: "{reqsJsonPath[0]['.metadata.name']['-']}"
                                  - type: antdFlex
                                    data:
                                      id: 14
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 15
                                          text: Namespace
                                          strong: true
                                      - type: antdLink
                                        data:
                                          id: 16
                                          text: "{reqsJsonPath[0]['.metadata.namespace']['-']}"
                                          href: "/openapi-ui/{2}/factory/namespace-details/{3}"
                                  - type: antdFlex
                                    data:
                                      id: 17
                                      vertical: true
                                      gap: 8
                                    children:
                                      - type: antdText
                                        data:
                                          id: 18
                                          text: Labels
                                          strong: true
                                          style:
                                            fontSize: 14
                                      - type: parsedText
                                        data:
                                          id: 19
                                          text: "No selector"
                                          style:
                                            color: red
                                  - type: antdFlex
                                    data:
                                      id: 20
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 21
                                          text: Annotations
                                          strong: true
                                      - type: parsedText
                                        data:
                                          id: 22
                                          text: "0 Annotations"
                                          style:
                                            color: red
                                  - type: antdFlex
                                    data:
                                      id: 23
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 24
                                          text: Created
                                          strong: true
                                      - type: antdFlex
                                        data:
                                          id: 25
                                          gap: 6
                                          align: center
                                        children:
                                          - type: antdText
                                            data:
                                              id: 26
                                              text: "🌐"
                                          - type: parsedText
                                            data:
                                              id: 27
                                              text: "{reqsJsonPath[0]['.metadata.creationTimestamp']['-']}"
                                  - type: antdFlex
                                    data:
                                      id: 28
                                      vertical: true
                                      gap: 4
                                    children:
                                      - type: antdText
                                        data:
                                          id: 29
                                          text: Owner
                                          strong: true
                                      - type: parsedText
                                        data:
                                          id: 351
                                          strong: true
                                          text: "No owner"
                                          style:
                                            color: red
              # YAML
              - key: yaml
                label: YAML
                children:
                  - type: YamlEditorSingleton
                    data:
                      id: 31
                      cluster: "{2}"
                      isNameSpaced: true
                      type: builtin
                      typeName: configmaps
                      prefillValuesRequestIndex: 0
                      substractHeight: 400
