---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-statefulset-details-volume-list"
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
  id: "factory-statefulset-details-volume-list"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-cluster-apps.v1.statefulsets"
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        {{ include "incloud-web-resources.icon" (dict
            "text" "SS"
            "title" "statefulset"
            "backgroundColor" "#2b9af3"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "statefulset-details"
          ) | nindent 12 
        }}
    - jsonPath: .metadata.namespace
      name: Namespace
      type: factory
      customProps:
        {{ include "incloud-web-resources.icon" (dict
            "text" "NS"
            "title" "namespace"
            "backgroundColor" "#1e4f18"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "namespace"
            "jsonPath" ".metadata.namespace"
            "factory" "namespace-details"
          ) | nindent 12
        }}
    - jsonPath: .metadata.labels
      name: Labels
      type: array
    - jsonPath: .spec.template.metadata.labels
      name: Pod Selector
      type: array
    - jsonPath: .status.conditions[?(@.type=="Available")].status
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
    - key: Labels
      value: 1
    - key: Pod Selector
      value: 1
  id: "stock-cluster-/apps/v1/statefulsets"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-namespace-apps.v1.statefulsets"
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        {{ include "incloud-web-resources.icon" (dict
            "text" "SS"
            "title" "statefulset"
            "backgroundColor" "#2b9af3"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "statefulset-details"
          ) | nindent 12 
        }}
    - jsonPath: .metadata.labels
      name: Labels
      type: array
    - jsonPath: .spec.template.metadata.labels
      name: Pod Selector
      type: array
    - jsonPath: .status.conditions[?(@.type=="Available")].status
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
    - key: Labels
      value: 1
    - key: Pod Selector
      value: 1
  id: "stock-namespace-/apps/v1/statefulsets"
