apiVersion: v1
items:
  - apiVersion: front.in-cloud.io/v1alpha1
    kind: CustomColumnsOverride
    metadata:
      name: "stock-cluster-batch.v1.jobs"
    spec:
      additionalPrinterColumns:
        - jsonPath: .metadata.name
          name: Name
          type: string
        - jsonPath: .metadata.namespace
          name: Namespace
          type: string
        - jsonPath: .spec.manualSelector
          name: Manual selector
          type: string
        - jsonPath: .spec.backoffLimit
          name: Backoff limit
          type: string
        - jsonPath: .spec.completions
          name: Completions
          type: string
        - jsonPath: .spec.parallelism
          name: Parallelism
          type: string
        - jsonPath: .spec.completionMode
          name: Completion mode
          type: string
        - jsonPath: .spec.suspend
          name: Suspend
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Created
          type: date
      additionalPrinterColumnsTrimLengths:
        - key: Name
          value: 64
      additionalPrinterColumnsUndefinedValues:
        - key: Namespace
          value: "-"
        - key: Starting deadline seconds
          value: "-"
      id: "stock-cluster-/batch/v1/jobs"

  - apiVersion: front.in-cloud.io/v1alpha1
    kind: CustomColumnsOverride
    metadata:
      name: "stock-namespace-batch.v1.jobs"
    spec:
      additionalPrinterColumns:
        - jsonPath: .metadata.name
          name: Name
          type: string
        - jsonPath: .spec.manualSelector
          name: Manual selector
          type: string
        - jsonPath: .spec.backoffLimit
          name: Backoff limit
          type: string
        - jsonPath: .spec.completions
          name: Completions
          type: string
        - jsonPath: .spec.parallelism
          name: Parallelism
          type: string
        - jsonPath: .spec.completionMode
          name: Completion mode
          type: string
        - jsonPath: .spec.suspend
          name: Suspend
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Created
          type: date
      additionalPrinterColumnsTrimLengths:
        - key: Name
          value: 64
      additionalPrinterColumnsUndefinedValues:
        - key: Namespace
          value: "-"
        - key: Starting deadline seconds
          value: "-"
      id: "stock-namespace-/batch/v1/jobs"

  - apiVersion: front.in-cloud.io/v1alpha1
    kind: CustomColumnsOverride
    metadata:
      name: "factory-batch.v1.jobs"
    spec:
      additionalPrinterColumns:
        - jsonPath: .metadata.name
          name: Name
          type: string
        - jsonPath: .spec.manualSelector
          name: Manual selector
          type: string
        - jsonPath: .spec.backoffLimit
          name: Backoff limit
          type: string
        - jsonPath: .spec.completions
          name: Completions
          type: string
        - jsonPath: .spec.parallelism
          name: Parallelism
          type: string
        - jsonPath: .spec.completionMode
          name: Completion mode
          type: string
        - jsonPath: .spec.suspend
          name: Suspend
          type: string
        - jsonPath: .spec.startingDeadlineSeconds
          name: Starting deadline seconds
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Created
          type: date
      additionalPrinterColumnsTrimLengths:
        - key: Name
          value: 64
      additionalPrinterColumnsUndefinedValues:
        - key: Namespace
          value: "-"
        - key: Starting deadline seconds
          value: "-"
      id: "factory-/batch/v1/jobs"

  - apiVersion: front.in-cloud.io/v1alpha1
    kind: CustomColumnsOverride
    metadata:
      name: "factory-job-details-init-containers-list"
    spec:
      additionalPrinterColumns:
        - jsonPath: .name
          name: Name
          type: string
        - jsonPath: .image
          name: Image
          type: string
        - jsonPath: .resources.requests
          name: Resources requests
          type: string
        - jsonPath: .resources.limits
          name: Resources limits
          type: string
      additionalPrinterColumnsTrimLengths:
        - key: Image
          value: 64
      additionalPrinterColumnsUndefinedValues:
        - key: Name
          value: "-"
        - key: Image
          value: "-"
        - key: Resources limits
          value: "-"
        - key: Resources requests
          value: "-"
      id: "factory-job-details-init-containers-list"

  - apiVersion: front.in-cloud.io/v1alpha1
    kind: CustomColumnsOverride
    metadata:
      name: "factory-job-details-containers-list"
    spec:
      additionalPrinterColumns:
        - jsonPath: .name
          name: Name
          type: string
        - jsonPath: .image
          name: Image
          type: string
        - jsonPath: .resources.requests
          name: Resources requests
          type: string
        - jsonPath: .resources.limits
          name: Resources limits
          type: string
        - jsonPath: .ports[*].containerPort
          name: Ports
          type: string
      additionalPrinterColumnsTrimLengths:
        - key: Image
          value: 64
      additionalPrinterColumnsUndefinedValues:
        - key: Name
          value: "-"
        - key: Image
          value: "-"
        - key: Resources limits
          value: "-"
        - key: Resources requests
          value: "-"
        - key: Ports
          value: "-"
      id: "factory-job-details-containers-list"

kind: List
metadata:
