---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-status-init-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .imageID
      name: Image
      type: string
    - jsonPath: .started
      name: Started
      type: string
    - jsonPath: .ready
      name: Ready
      type: string
    - jsonPath: .restartCount
      name: RestartCount
      type: string
    - jsonPath: .lastState.waiting.reason
      name: WaitingdReason
      type: string
    - jsonPath: .lastState.terminated.reason
      name: TerminatedReason
      type: string

  additionalPrinterColumnsUndefinedValues:
    - key: TerminatedReason
      value: "-"
    - key: WaitingdReason
      value: "-"

  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 63
    - key: Image
      value: 63
  id: "container-status-init-containers-list"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-status-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .imageID
      name: Image
      type: string
    - jsonPath: .started
      name: Started
      type: string
    - jsonPath: .ready
      name: Ready
      type: string
    - jsonPath: .restartCount
      name: RestartCount
      type: string
    - jsonPath: .lastState.waiting.reason
      name: WaitingdReason
      type: string
    - jsonPath: .lastState.terminated.reason
      name: TerminatedReason
      type: string

  additionalPrinterColumnsUndefinedValues:
    - key: TerminatedReason
      value: "-"
    - key: WaitingdReason
      value: "-"

  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 63
    - key: Image
      value: 63
  id: "container-status-containers-list"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-spec-init-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .image
      name: Image
      type: string
    - jsonPath: .resources.requests
      name: Resources requests
      type: string
    - jsonPath: .resources.limits
      name: Resources limits
      type: string
  additionalPrinterColumnsTrimLengths:
    - key: Image
      value: 64
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Image
      value: "-"
    - key: Resources limits
      value: "-"
    - key: Resources requests
      value: "-"
  id: container-spec-init-containers-list

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-spec-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .image
      name: Image
      type: string
    - jsonPath: .resources.requests
      name: Resources requests
      type: string
    - jsonPath: .resources.limits
      name: Resources limits
      type: string
    - jsonPath: .ports[*].containerPort
      name: Ports
      type: string
  additionalPrinterColumnsTrimLengths:
    - key: Image
      value: 64
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Image
      value: "-"
    - key: Resources limits
      value: "-"
    - key: Resources requests
      value: "-"
    - key: Ports
      value: "-"
  id: container-spec-containers-list