---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-rbac.authorization.k8s.io.v1.clusterroles
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "CR"
            "title" "clusterrole"
            "backgroundColor" "#c46100"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "factory" "clusterrole-details"
          ) | nindent 12 
        }}
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
  id: stock-cluster-/rbac.authorization.k8s.io/v1/clusterroles