---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-v1.serviceaccounts
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "SA"
            "title" "serviceaccount"
            "backgroundColor" "#b48c78ff"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "serviceaccount-details"
          ) | nindent 12 
        }}
    - jsonPath: .metadata.namespace
      name: Namespace
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "NS"
            "title" "namespace"
            "backgroundColor" "#a25792ff"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "namespace"
            "jsonPath" ".metadata.namespace"
            "factory" "namespace-details"
          ) | nindent 12
        }}
    - jsonPath: .secrets[*].name
      name: Secrets
      type: array
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsUndefinedValues:
    - key: Namespace
      value: "-"
    - key: Secrets
      value: "-"
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
    - key: Secrets
      value: 1
  id: stock-cluster-/v1/serviceaccounts

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-namespace-v1.serviceaccounts
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "SA"
            "title" "serviceaccount"
            "backgroundColor" "#b48c78ff"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "serviceaccount-details"
        ) | nindent 12 
        }}
    - jsonPath: .secrets
      name: Secrets
      type: array
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsUndefinedValues:
    - key: Secrets
      value: "-"
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
    - key: Secrets
      value: 1
  id: stock-namespace-/v1/serviceaccounts

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: factory-serviceaccount-secrets
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "S"
            "title" "secret"
            "backgroundColor" "#c46100"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "secret-details"
          ) | nindent 12 
        }}
  id: factory-serviceaccount-secrets
