apiVersion: v1
items:
  - apiVersion: front.in-cloud.io/v1alpha1
    kind: TableUriMapping
    metadata:
      name: crd-details
    spec:
      keysToParse:
        - metadata
        - name
      id: "default-/apiextensions.k8s.io/v1/customresourcedefinitions"
      pathToNavigate: "/openapi-ui/{clusterName}/factory/crd-details/~recordValue~"

kind: List
metadata:
