apiVersion: v1
items:
  - apiVersion: front.in-cloud.io/v1alpha1
    kind: TableUriMapping
    metadata:
      name: cluster-infra-details
    spec:
      keysToParse:
        - metadata
        - name
      keysToParseSecond:
        - metadata
        - namespace
      id: "factory-cluster-infra-/cluster.x-k8s.io/v1beta1/clusters"
      pathToNavigate: "/openapi-ui/{2}/~recordValueSecond~/factory/cluster-infra-details/~recordValue~"

  - apiVersion: front.in-cloud.io/v1alpha1
    kind: TableUriMapping
    metadata:
      name: cluster-client-details
    spec:
      keysToParse:
        - metadata
        - name
      keysToParseSecond:
        - metadata
        - namespace
      id: "factory-cluster-client-/cluster.x-k8s.io/v1beta1/clusters"
      pathToNavigate: "/openapi-ui/{2}/~recordValueSecond~/factory/cluster-client-details/~recordValue~"

kind: List
metadata:
