{{- if .Values.addons.argocd.enabled  }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-cluster-argoproj.io.v1alpha1.applications"
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "A"
            "title" "applications"
            "backgroundColor" "#436853ff"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "argocd-application-details"
        ) | nindent 12 
        }}
    - jsonPath: .metadata.namespace
      name: Namespace
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "NS"
            "title" "namespace"
            "backgroundColor" "#a25792ff"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "namespace"
            "jsonPath" ".metadata.namespace"
            "factory" "namespace-details"
          ) | nindent 12
        }}
    - jsonPath: .status.sync.status
      name: Sync Status
      type: string
    - jsonPath: .status.health.status
      name: Health Status
      type: string
    - jsonPath: .status.sync.revision
      name: Revision
      type: string
    - jsonPath: .spec.project
      name: Project
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsTrimLengths: []
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Sync Status
      value: "-"
    - key: Health Status
      value: "-"
    - key: Revision
      value: "-"
    - key: Project
      value: "-"

  id: "stock-cluster-/argoproj.io/v1alpha1/applications"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-namespace-argoproj.io.v1alpha1.applications"
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "A"
            "title" "applications"
            "backgroundColor" "#436853ff"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
            "factory" "argocd-application-details"
        ) | nindent 12 
        }}
    - jsonPath: .status.sync.status
      name: Sync Status
      type: string
    - jsonPath: .status.health.status
      name: Health Status
      type: string
    - jsonPath: .status.sync.revision
      name: Revision
      type: string
    - jsonPath: .spec.project
      name: Project
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsTrimLengths: []

  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Sync Status
      value: "-"
    - key: Health Status
      value: "-"
    - key: Revision
      value: "-"
    - key: Project
      value: "-"

  id: "stock-namespace-/argoproj.io/v1alpha1/applications"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: factory-argocd-application-resources
spec:
  additionalPrinterColumns:
    - jsonPath: .kind
      name: Kind
      type: string
    - jsonPath: .version
      name: Version
      type: string
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .namespace
      name: Namespace
      type: string
    - jsonPath: .status
      name: Status
      type: string
    - jsonPath: .message
      name: Message
      type: string

  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
    - key: Message
      value: 64
  additionalPrinterColumnsUndefinedValues:
    - key: Message
      value: "-"
    - key: Namespace
      value: "-"

  id: "factory-argocd-application-resources"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-argocd-application-status-resources"
spec:
  additionalPrinterColumns:
    - jsonPath: .kind
      name: Kind
      type: string
    - jsonPath: .version
      name: Version
      type: string
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .namespace
      name: Namespace
      type: string
    - jsonPath: .status
      name: Status
      type: string
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
  additionalPrinterColumnsUndefinedValues:
    - key: Namespace
      value: "-"

  id: "factory-argocd-application-status-resources"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-argocd-application-status-history"
spec:
  additionalPrinterColumns:
    - jsonPath: .id
      name: ID
      type: string
    - jsonPath: .initiatedBy.username
      name: InitiatedBy
      type: string
    - jsonPath: .deployStartedAt
      name: Deploy Started At
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".deployStartedAt"
          ) | nindent 8
        }}
    - jsonPath: .deployedAt
      name: Deployed At
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".deployedAt"
          ) | nindent 8
        }}
    - jsonPath: .revision
      name: Revision
      type: string
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
  additionalPrinterColumnsUndefinedValues:
    - key: Namespace
      value: "-"
    - key: Revision
      value: "-"
  id: "factory-argocd-application-status-history"

{{- end -}}