---
apiVersion: front.in-cloud.io/v1alpha1
kind: Sidebar
metadata:
  name: stock-project-factory-configmap-details
spec:
  id: stock-project-factory-configmap-details
  keysAndTags:
    configmaps:
      - configmap-sidebar
  menuItems:
    {{ include "incloud-web-resources.sidebar.menu.items.namespaced" . | nindent 4 }}
