---
apiVersion: front.in-cloud.io/v1alpha1
kind: Sidebar
metadata:
  name: stock-project-factory-pod-details
spec:
  id: stock-project-factory-pod-details
  keysAndTags:
    pods:
      - pods-sidebar
  menuItems:
    {{ include "incloud-web-resources.sidebar.menu.items.namespaced" . | nindent 4 }}
