---
apiVersion: front.in-cloud.io/v1alpha1
kind: Sidebar
metadata:
  name: stock-project-factory-poddisruptionbudget-details
spec:
  id: stock-project-factory-poddisruptionbudget-details
  keysAndTags:
    poddisruptionbudgets:
      - poddisruptionbudget-sidebar
  menuItems:
    {{ include "incloud-web-resources.sidebar.menu.items.namespaced" . | nindent 4 }}
