{{- if .Values.addons.trivy.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-aquasecurity.github.io.v1alpha1.vulnerabilityreports"
spec:
  additionalPrinterColumns:
    - jsonPath: .severity
      name: Severity
      type: string
    - jsonPath: .vulnerabilityID
      name: Vulnerability ID
      type: string
    - jsonPath: .installedVersion
      name: Installed version
      type: string
    - jsonPath: .fixedVersion
      name: Fixed version
      type: string
    - jsonPath: .score
      name: Score
      type: string
    - jsonPath: .resource
      name: Resource
      type: string
  additionalPrinterColumnsUndefinedValues:
    - key: Severity
      value: "-"
    - key: Vulnerability ID
      value: "-"
    - key: Installed version
      value: "-"
    - key: Fixed version
      value: "-"
    - key: Score
      value: "-"
    - key: Resource
      value: "-"
  id: "factory-aquasecurity.github.io.v1alpha1.vulnerabilityreports"
{{- end -}}
