---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-deployment-details
spec:
  id: "stock-project-factory-deployment-details"
  breadcrumbItems:
    - key: deployments
      label: "apps/v1/deployments"
      link: "/openapi-ui/{clusterName}/{namespace}/api-table/apps/v1/deployments"
    - key: Deployment
      label: "{6}"
