---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-serviceaccount-details
spec:
  id: "stock-project-factory-serviceaccount-details"
  breadcrumbItems:
    - key: serviceaccounts
      label: "v1/serviceaccounts"
      link: "/openapi-ui/{clusterName}/{namespace}/builtin-table/serviceaccounts"
    - key: serviceaccount
      label: "{6}"
