name: release
on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

env:
  CHART_DIR: .
  REGISTRY: registry-1.docker.io
  OWNER: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package & Push
        run: |
          pkg=$(helm package "${{ env.CHART_DIR }}" | awk '{print $NF}')
          helm registry login registry-1.docker.io -u prorobotech -p ${{ secrets.DOCKERHUB_TOKEN }}
          helm push $pkg oci://registry-1.docker.io/prorobotech
